apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app 
          image: markpollack/spring-sample-app:1.0.0 # REPLACE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
          name: app
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
