apiVersion: v1
data:
  SPRING_PROFILES_ACTIVE: dev
kind: ConfigMap
metadata:
  name: spring-configmap-env-c49bfhc52b
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mark-spring-sample-app
  name: mark-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: mark-spring-sample-app
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mark-spring-sample-app
  name: mark-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mark-spring-sample-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mark-spring-sample-app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: spring-configmap-env-c49bfhc52b
        image: markpollack/spring-sample-app:1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
